apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubediag-dashboard-role
rules:
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operations/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - diagnoses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - diagnoses/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - operationsets/status
  verbs:
  - get
  - patch
  - update
    
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - triggers/status
  verbs:
  - get
  - patch
  - update
